---

- hosts: all
  become: true
  pre_tasks:

  - name: updates repo (CentOS)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: updates repo (ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- hosts: all
  become: true
  tasks:


- hosts: web_servers
  become: true
  roles:
    - workstations

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers

- hosts: workstations
  become: true
  roles:
    - workstations

