- name: install mariadb for CentOS servers
  tags: db, maria, centos
  dnf:
    name:
      - mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb for Ubuntu servers
  tags: db, maris, centos
  apt:
    name:
      - mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
